CREATE TABLE IF NOT EXISTS current_anime (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  guildId VARCHAR(32) NOT NULL,
  animeId INT UNSIGNED NOT NULL,
  animeTitle VARCHAR(255) NOT NULL,
  currentEpisode INT UNSIGNED DEFAULT 1,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS watch_parties (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  guildId VARCHAR(32) NOT NULL,
  animeId VARCHAR(64) NOT NULL,
  animeTitle VARCHAR(255) NOT NULL,
  coverImage TEXT,
  currentEpisode INT UNSIGNED DEFAULT 1,
  season VARCHAR(32),
  day VARCHAR(16),
  time VARCHAR(16),
  duration VARCHAR(16),
  repeat BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

ALTER TABLE watch_parties
ADD COLUMN IF NOT EXISTS eventStartTime DATETIME DEFAULT NULL,
ADD COLUMN IF NOT EXISTS eventEndTime DATETIME DEFAULT NULL,
ADD COLUMN IF NOT EXISTS paused BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS scheduledEventId VARCHAR(255) DEFAULT NULL